---
# ---------------------------------------------------------------------------------
# $Id$
# Copyright 2014 sampnt@ Alcatel-lucent
# ---------------------------------------------------------------------------------
- name: Install tuned and ksm
  yum: name={{item}} state=present
  with_items:
    - tuned
#    - tuned-utils
  environment: proxy_env

- name: Enable and start tuned/ksm 
  service: name={{item}} state=started enabled=true
  with_items:
    - tuned
    - ksm

- name: Setup tuned profile to virtual-host
  command: tuned-adm profile virtual-host 
      
- name: Config tuned.conf
  copy: src=tuned.conf dest=/etc/tune-profiles/virtual-host/tuned.conf
  notify: restart tuned
  
- name: Config sysctl.ktune
  copy: src=sysctl.ktune dest=/etc/tune-profiles/virtual-host/sysctl.ktune
  notify: restart tuned
  
- name: Config sshd
  lineinfile: 
    backup=yes state=present dest=/etc/ssh/sshd_config backrefs=yes
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - { regexp: '^#MaxSessions', line: 'MaxSessions 100' }   
    - { regexp: '^#MaxStartups', line: 'MaxStartups 100' }
    - { regexp: '^#UseDNS yes', line: 'UseDNS no'}
    - { regexp: '^GSSAPIAuthentication yes', line: 'GSSAPIAuthentication no'}
  notify: restart sshd