---
# ---------------------------------------------------------------------------------
# $Id$
# Copyright 2014 sampnt@ Alcatel-lucent
# ---------------------------------------------------------------------------------
- name: config libvirt
  lineinfile: 
    backup=yes state=present dest=/etc/sysconfig/libvirtd backrefs=yes
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - { regexp: '^#LIBVIRTD_ARGS', line: 'LIBVIRTD_ARGS="--listen"' }
    - { regexp: '^#LIBVIRTD_CONFIG', line: 'LIBVIRTD_CONFIG=/etc/libvirt/libvirtd.conf' }
  notify: restart libvirtd   
 
- name: Config libvirtd
  lineinfile: 
    backup=yes state=present dest=/etc/libvirt/libvirtd.conf backrefs=yes
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - { regexp: '^#listen_tls', line: 'listen_tls = 0' }   
    - { regexp: '^#listen_tcp', line: 'listen_tcp = 1' }
    - { regexp: '^#tcp_port', line: 'tcp_port = "16509"' }
    - { regexp: '^#unix_sock_group', line: 'unix_sock_group = "{{one_user_name}}"' }
    - { regexp: '^#auth_unix_ro', line: 'auth_unix_ro = "none"' }
    - { regexp: '^#auth_unix_rw', line: 'auth_unix_rw = "none"' }
    - { regexp: '^#auth_tcp', line: 'auth_tcp = "none"' }
    - { regexp: '^#max_clients', line: 'max_clients = 2048' }
    - { regexp: '^#min_workers', line: 'min_workers = 10' }
    - { regexp: '^#max_workers', line: 'max_workers = 400"' }
    - { regexp: '^#max_requests', line: 'max_requests = 2000' }
    - { regexp: '^#max_client_requests', line: 'max_client_requests = 400' }
  notify: restart libvirtd
