---
# ---------------------------------------------------------------------------------
# $Id$
# Copyright 2014 sampnt@ Alcatel-lucent
# ---------------------------------------------------------------------------------
- name: Stop/Disable unused services 
  service: name={{item}} state=stopped enabled=false
  with_items:
    - NetworkManager
    - bluetooth
    - httpd
    - ipsec
    - jexec
    - ksmtuned
    - libvirt-guests
    - named
    - openct
    - pcscd
    - postfix
    - rhnsd
    - rhsmcertd
    - spice-vdagentd
    - svnserve
    - sysstat
    - virt-who
    - vncserver
    - vsftpd
    - wine
    - wpa_supplicant   

- name: Enable NIS in Name Service Switch config
  lineinfile: 
    state=present dest=/etc/nsswitch.conf backrefs=yes
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - { regexp: '^#passwd:', line: 'passwd:     files nis' }   
    - { regexp: '^#shadow:', line: 'shadow:     files nis' }
    - { regexp: '^#group:', line: 'group:     files nis' }

- name: Change default runlevel
  lineinfile: 
    state=present dest=/etc/inittab backrefs=yes
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - { regexp: '^id:5:initdefault:', line: 'id:3:initdefault:' }

- name: Reove local user authentication key
  authorized_key: user=root key="{{ lookup('file', '/home/genel/.ssh/id_rsa.pub') }}" state=absent   