---
# ---------------------------------------------------------------------------------
# $Id$
# Copyright 2014 sampnt@ Alcatel-lucent
# ---------------------------------------------------------------------------------

#- name: Copy the EPEL repository definition
#  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo

#- name: Create the GPG key for EPEL
#  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: Disable NIS in Name Service Switch config
  lineinfile: 
    backup=yes state=present dest=/etc/nsswitch.conf backrefs=yes
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - { regexp: '^passwd:', line: '#passwd:     files nis' }   
    - { regexp: '^shadow:', line: '#shadow:     files nis' }
    - { regexp: '^group:', line: '#group:     files nis' }
    
- name: Setup one group oneadmin
  group: name="{{ one_group_name }}" gid="{{ one_group_id }}" state=present

- name: Setup one user oneadmin
  user: name="{{ one_user_name }}" group="{{ one_group_name }}" home="{{ one_user_home }}" 
    uid="{{ one_user_id }}" password="{{ one_user_password }}"
    
- name: Change super user password 
  user: name="root" password="{{ new_superuser_password }}"  

- name: Umount /etc/fstab
  command: "{{item}}"
  with_items:
    - mount -a
    - umount /var/lib/one/tools
    - umount /var/lib/one/datastores/100
    - umount /vm/cache_on_server
  ignore_errors: yes
     
- name: Setup oneadmin home ownership
  file: path="{{ one_user_home }}" state=directory owner="{{ one_user_name }}" group="{{ one_group_name }}" recurse=true

- name: Remount /etc/fstab
  command: mount -a
  
- name: Install ntp
  yum: name=ntp state=present
  
- name: Install htop
  yum: name=htop state=present  
  
- name: Start/enable ntp
  service: name=ntpd state=started enabled=true  

# Consider to setup the server directly instead of a template
- name: Create ntp configuration file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntpd

- name: Stop/disable iptables
  service: name={{ item }} state=stopped enabled=false
  with_items:
    - iptables
    - ip6tables
  
- name: Config/disable Selinux
  selinux: policy=targeted state=disabled