---
# ---------------------------------------------------------------------------------
# $Id$
# Copyright 2014 sampnt@ Alcatel-lucent
# ---------------------------------------------------------------------------------

#- name: Copy the EPEL repository definition
#  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo

#- name: Create the GPG key for EPEL
#  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: Disable NIS in Name Service Switch config

- name: Setup one group oneadmin

- name: Setup one user oneadmin

- name: Install ntp
  yum: name=libselinux-python state=present

- name: Set up ntp
  copy: src=iptables-save dest=/etc/sysconfig/iptables
  notify: restart network
 
# Its good to turn on again. We dont because we have zabbix installation later 
#- name: Enable NIS in Name Service Switch config
