---
# ---------------------------------------------------------------------------------
# $Id$
# Copyright 2014 sampnt@ Alcatel-lucent
# ---------------------------------------------------------------------------------
- name: Setup OpenNebula repo
  template: src=one.repo.j2 dest=/etc/yum.repos.d/one.repo
 
- name: Install OpenNebula node and its dependencies
  yum: name={{item}} state=present
  with_items:
    - opennebula-node-kvm-{{ one_version }}
  environment: proxy_env
   
- name: Create one-kvm-rules
  copy: src=60-qemu-kvm.rules dest=/etc/udev/rules.d/60-qemu-kvm.rules