---
- name: Install OpenNebula, setup bridge and tunning
  hosts: kanata
#  hosts: bangalore
#  accelerate: true
  user: root
  # remote_user: user
  # sudo: yes

  roles:
    - common
    - one
    - libvirt
    - ssh-keys
    - network
    - tuned
    - zabbix
    - cleanup
