---
# ---------------------------------------------------------------------------------
# $Id$
# Copyright 2014 sampnt@ Alcatel-lucent
# ---------------------------------------------------------------------------------

- name: Set up authorized_keys for the oneadmin user
  authorized_key: user=oneadmin
                  key="{{ item }}"
  with_file:
    - one_samcloud_id_rsa.pub
    - one_vmpnttools_id_rsa.pub
    
- name: Set up authorized_keys for the super user
  authorized_key: user=root
                  key="{{ item }}"
  with_file:
    - one_samcloud_id_rsa.pub