---
# ---------------------------------------------------------------------------------
# $Id$
# Copyright 2014 sampnt@ Alcatel-lucent
# ---------------------------------------------------------------------------------

- name: Set up authorized_keys for the oneadmin user
  authorized_key: user=oneadmin
                  key="{{ item }}"
  with_file:
    - "{{ samcloud_oneadmin_pub_key }}"
    - "{{ samvmmgr_oneadmin_pub_key }}"
    
- name: Set up authorized_keys for the super user
  authorized_key: user=root
                  key="{{ item }}"
  with_file:
    - "{{ samcloud_oneadmin_pub_key }}"