---
# ---------------------------------------------------------------------------------
# $Id$
# Copyright 2014 sampnt@ Alcatel-lucent
# ---------------------------------------------------------------------------------
- name: install the zabbix repo
  yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm state=present
  
- name: install zabbix agent
  yum: name=zabbix-agent state=present  
  
- name: Start/enable zabbix_agent
  service: name=zabbix-agent state=started enabled=true  

- name: Create zabbix agent configuration file from template
  template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
  notify: restart zabbix-agent
 
- name: Copy sudoers file for safety
  command: cp -f /etc/sudoers /etc/sudoers.tmp
  register: sudoers_tmp

- name: Create sudoers file backup
  command: cp -f /etc/sudoers /etc/sudoers.bak

- name: Make sure sudo does not require tty
  lineinfile: dest=/etc/sudoers.tmp state=present regexp='^Defaults    requiretty' line='Defaults    !requiretty' backrefs=yes
  when: sudoers_tmp|changed

- name: Make sure zabbix-agent works via sudo
  lineinfile: "dest=/etc/sudoers.tmp state=present regexp='^zabbix ALL=NOPASSWD' line='zabbix ALL=NOPASSWD: /sbin/service libvirtd restart'"
  when: sudoers_tmp|changed

- name: Final sudoers file check
  shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers && rm -f /etc/sudoers.tmp
